git add "Fragments/learning-fragment/src/App.css"
git commit -m "update global styles for learning fragment"
git add "Fragments/learning-fragment/src/App.jsx"
git commit -m "update main app component for learning fragment"
git add "Fragments/learning-fragment/src/components/item.jsx"
git commit -m "update item component for learning fragment"
git add "Fragments/learning-fragment/src/components/item.module.css"
git commit -m "add item component styles"
git add "git_push.bat"
git commit -m "add batch script for git push"
git add "package-lock.json"
git commit -m "update root dependency lockfile"
git add "package.json"
git commit -m "update root dependency configuration"
git add "projects/Calculator-version-one/.gitignore"
git commit -m "add gitignore for calculator project"
git add "projects/Calculator-version-one/README.md"
git commit -m "add readme for calculator project"
git add "projects/Calculator-version-one/eslint.config.js"
git commit -m "add eslint configuration for calculator project"
git add "projects/Calculator-version-one/index.html"
git commit -m "add entry point file for calculator project"
git add "projects/Calculator-version-one/package-lock.json"
git commit -m "add dependency lockfile for calculator project"
git add "projects/Calculator-version-one/package.json"
git commit -m "add dependency configuration for calculator project"
git add "projects/Calculator-version-one/public/vite.svg"
git commit -m "add vite logo for calculator project"
git add "projects/Calculator-version-one/src/App.jsx"
git commit -m "add main app component for calculator project"
git add "projects/Calculator-version-one/src/App.module.css"
git commit -m "add main app styles for calculator project"
git add "projects/Calculator-version-one/src/assets/react.svg"
git commit -m "add react logo for calculator project"
git add "projects/Calculator-version-one/src/components/ButtonsContainer.jsx"
git commit -m "add buttons container component for calculator project"
git add "projects/Calculator-version-one/src/components/ButtonsContainer.module.css"
git commit -m "add buttons container styles for calculator project"
git add "projects/Calculator-version-one/src/components/Display.jsx"
git commit -m "add display component for calculator project"
git add "projects/Calculator-version-one/src/components/Display.module.css"
git commit -m "add display styles for calculator project"
git add "projects/Calculator-version-one/src/main.jsx"
git commit -m "add main entry script for calculator project"
git add "projects/Calculator-version-one/vite.config.js"
git commit -m "add vite configuration for calculator project"
git add "projects/todo-app-version-two/.gitignore"
git commit -m "add gitignore for todo app"
git add "projects/todo-app-version-two/README.md"
git commit -m "add readme for todo app"
git add "projects/todo-app-version-two/eslint.config.js"
git commit -m "add eslint configuration for todo app"
git add "projects/todo-app-version-two/index.html"
git commit -m "add entry point file for todo app"
git add "projects/todo-app-version-two/package-lock.json"
git commit -m "add dependency lockfile for todo app"
git add "projects/todo-app-version-two/package.json"
git commit -m "add dependency configuration for todo app"
git add "projects/todo-app-version-two/public/vite.svg"
git commit -m "add vite logo for todo app"
git add "projects/todo-app-version-two/src/App.css"
git commit -m "add global styles for todo app"
git add "projects/todo-app-version-two/src/App.jsx"
git commit -m "add main app component for todo app"
git add "projects/todo-app-version-two/src/Component/AddTodo.jsx"
git commit -m "add add todo component for todo app"
git add "projects/todo-app-version-two/src/Component/AppName.jsx"
git commit -m "add app name component for todo app"
git add "projects/todo-app-version-two/src/Component/TodoItem.jsx"
git commit -m "add todo item component for todo app"
git add "projects/todo-app-version-two/src/assets/react.svg"
git commit -m "add react logo for todo app"
git add "projects/todo-app-version-two/src/main.jsx"
git commit -m "add main entry script for todo app"
git add "projects/todo-app-version-two/vite.config.js"
git commit -m "add vite configuration for todo app"
git add "run_git.ps1"
git commit -m "add powershell script for git operations"
git push
