git add "README.md"
git commit -m "docs: add professional README with project overview and tech stack"
git add "react/README.md"
git commit -m "docs: add professional README for React starter project"
git add "Fragments/learning-fragment/README.md"
git commit -m "docs: add professional README for Fragments learning project"
git add "BootStrap/prec/README.md"
git commit -m "docs: add professional README for Bootstrap practice project"
git add "projects/Calculator-version-one/README.md"
git commit -m "docs: add professional README for Calculator v1 project"
git add "projects/bharat-clock-version-1/README.md"
git commit -m "docs: add professional README for Bharat Clock v1 project"
git add "projects/todo-app-version-one/README.md"
git commit -m "docs: add professional README for Todo App v1 project"
git add "projects/todo-app-version-two/README.md"
git commit -m "docs: add professional README for Todo App v2 project"
git push
